{
    'name': 'Consignment RFQ Portal Cart',
    'summary': 'Portal consigner cart flow to submit purchase RFQs',
    'version': '18.0.1.0.0',
    'category': 'Purchases',
    'author': 'Odoo Community',
    'license': 'LGPL-3',
    'depends': ['purchase', 'portal', 'website', 'mail'],
    'data': [
        'security/rfq_portal_rules.xml',
        'security/ir.model.access.csv',
        'views/product_views.xml',
        'views/partner_views.xml',
        'views/purchase_order_views.xml',
        'views/portal_menu.xml',
        'templates/portal_consign_landing.xml',
        'templates/portal_rfq_products.xml',
        'templates/portal_rfq_cart.xml',
        'templates/portal_rfq_list.xml',
        'templates/portal_rfq_detail.xml',
    ],
    'installable': True,
    'application': False,
}
